import urllib.request

print("+"*63)
print("="*20, "Barix Reboot Tool", "="*20)
print("+"*63)
print("")
print("Status 200 = GOOD")
print("Status 404 = BAD")
print("")
print("Rebooting Lane 1")
get_url= urllib.request.urlopen('http://link.to.barix')
print("Response Status: "+ str(get_url.getcode()))
print("")
print("Rebooting Lane 2")
get_url= urllib.request.urlopen('http://link.to.barix')
print("Response Status: "+ str(get_url.getcode()))
print("")
